# 公開直後の侵害された可能性のあるリリースを避けるため、公開から3日（4320分）経過したバージョンのみ許可する
minimumReleaseAge: 4320

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vite-plus: 0.2.9
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
minimumReleaseAgeExclude:
  - vite-plus
  - "@voidzero-dev/*"
  - oxlint
  - "@oxlint/*"
  - oxlint-tsgolint
  - "@oxlint-tsgolint/*"
  - oxfmt
  - "@oxfmt/*"
