name: ci

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [check, test]
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: voidzero-dev/setup-vp@313600b80b104eadebb9111787d37a2e83e014ca # v1.17.0
        with:
          node-version: "24.19.0"
          cache: true
          run-install: true
      - run: vp ${{ matrix.task }}
